# Generated by Django 3.1.2 on 2020-11-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='id',
        ),
        migrations.AlterField(
            model_name='fridge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='FridgeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_today_ingredient', models.BooleanField(default=False)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.fridge')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='ingredients',
            field=models.ManyToManyField(through='user.FridgeIngredient', to='ingredient.Ingredient'),
        ),
    ]
