# Generated by Django 3.1.2 on 2020-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201210_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='naengpa_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='region_range',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
