# Generated by Django 3.1.2 on 2020-12-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201213_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_range', models.PositiveIntegerField(db_index=True, default=3)),
                ('from_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.region')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='user.region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='neighborhood',
            field=models.ManyToManyField(related_name='_region_neighborhood_+', through='user.NeighborhoodRegion', to='user.Region'),
        ),
    ]
