# Generated by Django 3.1.2 on 2020-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201110_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naengpa_score',
            field=models.IntegerField(default=0),
        ),
    ]
