# Generated by Django 3.1.2 on 2020-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201210_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
