# Generated by Django 3.1.2 on 2020-12-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201213_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neighborhoodregion',
            unique_together={('from_region', 'neighborhood', 'region_range')},
        ),
    ]
