# Generated by Django 3.1.2 on 2020-12-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201127_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region_range',
            field=models.IntegerField(default=0),
        ),
    ]
