# Generated by Django 3.1.2 on 2020-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fridgeingredient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
