os: linux
dist: xenial
language: python
python: 3.7
node_js: 12
cache:
  - yarn: true
  - pip: true

    - language: python
      python: "3.7"
      cache: pip
      before_install:
        - cd backend/naengpa
      install:
        - pip install -r requirements.txt
        - pip install coveralls
      script:
        - pylint **/*.py
        - coverage run --source='.' manage.py test
        - coverage xml
      after_success:
        - coveralls
        - cd ../..

install:
  - cd $FRONTEND && npm install yarn && yarn && yarn add coveralls
  - cd ../../$BACKEND && pip3 install -r requirements.txt
  - gem install coveralls-lcov

script:
  - echo "[Frontend scripts]"
  - cd ../../$FRONTEND && yarn lint
  - yarn test
  - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json

  - echo "[Backend scripts]"
  - cd ../../$BACKEND && pylint **/*.py
  - coverage run --branch --source='.' manage.py test && coverage report -m
  - coverage xml

  - echo "[Sonar scanner]"
  - cd ../.. && sonar-scanner

after_success:
  - cd $BACKEND
  - coveralls --merge=../../$FRONTEND/coverage/coverage.json
