jobs:
  include:
    - language: node_js
      dist: bionic
      node_js: "12"
      python: "3.7"
      cache:
        - pip: true
        - yarn: true
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: FJ3gXitz8KWhOeJIECTpAxcF8yaiU33BLrfD405pKBjp0vhSKBRorOwoU4hvNIAxE9StgsJ6HYdlt6S2mNZVnMbVibuzMi0xaikKKah9Yq+LfWxwixJ2TcsRSFSzcYiGWQ/P+Lna4eFH0l5IqrYNx0zlu0vzm+x/VBWIR+wziQV+jjLPi/hOkG+sqgFB/+UwbNfGPY+17x2A1D09p/LziEzB5kTtP/c1vdL1L1l+LDDQoq5dtbGEyEWWyDEr1sQEe8utTxnk2hDVgqO4j4q4nYrsIdqeZnF0/agjouY5ppeGLXuxQon8X6igT3o5CpgzhK/qeXclC1yvbdxB+WnhggGm1Kq90FfpDjzoO0pu+jlqA/6OBOgoCWv8RclxaD98yBy2bBR3bcCFtKIvMtC3wUvTAVVboUdmxL8x92h4MKqgCeqoU6SzQcBN4ZYoD2iUledR1ObD+FmWRjOONRMyjHtFLr3F7sZnLNAD376x6cxgNgwTZzopLAI8J8cBZOsydch1ud9qfmVIpBqMmZK2XFNqQk94Ob2MzS4SUlzODj2MMcoTBsIFxUdui4nedDRDGs0CRucN6n1tmVVOquYIQzL+h+2F1E3wNY76kXO1Kdn9qt3Akoj6soW4KUFpEB/FEJqD3itAgWx+uMtr3Mgp0hH9y1fs7aybsSivlM2+OIE=
      install:
        - cd frontend/naengpa
        - yarn
        - yarn global add coveralls
        - gem install coveralls-lcov
        - cd ../..
        - cd backend/naengpa
        - source ~/virtualenv/python3.7/bin/activate
        - sudo redis-server --daemonize yes
        - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt update
        - sudo apt update && sudo apt -y install gdal-bin libgdal-dev
        - ogrinfo --version
        - pip install -r requirements.txt
        - pip install coveralls
        - cd ../..
      script:
        - cd frontend/naengpa
        - yarn lint
        - yarn test
        - cd ../..
        - cd backend/naengpa
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ../..
        - sonar-scanner
        - cd frontend/naengpa
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../..
        - cd backend/naengpa
        - coveralls --merge=../../frontend/naengpa/coverage.json
        - cd ../..
    - language: node_js
      node_js:
        - "12"
      cache: yarn
      before_install:
        - cd frontend/naengpa
      install:
        - yarn
      script:
        - yarn lint
        - yarn test
    - language: python
      dist: bionic
      python: "3.7"
      cache: pip
      before_install:
        - cd backend/naengpa
      install:
        - source ~/virtualenv/python3.7/bin/activate
        - sudo redis-server --daemonize yes
        - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt update
        - sudo apt update && sudo apt -y install gdal-bin
        - pip install -r requirements.txt
        - pip install coveralls
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage report -m
# before_install:
#   - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
#     -in deploy_rsa.enc -out deploy_rsa -d
#   - eval "$(ssh-agent -s)"
#   - chmod 600 deploy_rsa
#   - ssh-add deploy_rsa
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: ssh ubuntu@54.225.50.176 'bash ./setup-deploy.sh && bash ./deploy.sh'
#   on:
#     branch: master
