// USER related ACTIONS
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const SIGNUP = 'SINGUP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER = 'GET_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

// FRIDGE related ACTIONS
export const GET_FRIDGE = 'GET_FRIDGE';
export const ADD_INGREDIENT_TO_FRIDGE = 'ADD_INGREDIENT_TO_FRIDGE';
export const DELETE_INGREDIENT_FROM_FRIDGE = 'DELETE_INGREDIENT_FROM_FRIDGE';
export const TOGGLE_TODAY_INGREDIENT = 'TOGGLE_TODAY_INGREDIENT';
export const ADD_INGREDIENT_TO_TODAY_INGREDIENT = 'ADD_INGREDIENT_TO_TODAY_INGREDIENT';

// RECIPE related ACTIONS
export const GET_RECIPE_LIST = 'GET_RECIPE_LIST';
export const GET_RECIPE = 'GET_RECIPE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';

// INGREDIENT related ACTIONS
export const GET_INGREDIENT_LIST = 'GET_INGREDIENT_LIST';
export const GET_INGREDIENT = 'GET_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT';

// ARTICLE related ACTIONS
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const GET_ARTICLE = 'GET_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';

// COMMENT related ACTIONS
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST';
export const GET_COMMENT = 'GET_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
