# Generated by Django 3.1.2 on 2020-12-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
