# Generated by Django 3.1.2 on 2020-12-10 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_members',
            field=models.ManyToManyField(blank=True, related_name='chatroom', through='chatroom.ChatMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_member', to='chatroom.chatroom'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
