# Generated by Django 3.1.2 on 2020-12-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
